# syntax=docker/dockerfile:1
FROM debian:12-slim

RUN apt-get -qq update \
    && apt-get -qq install -y --no-install-recommends \
        make \
        g++-mingw-w64-x86-64-win32 g++-mingw-w64-i686-win32
