# syntax=docker/dockerfile:1
FROM --platform=linux/amd64 debian:12-slim

ARG NDK_VERSION=r26c

RUN apt-get -qq update \
    && apt-get -qq install -y --no-install-recommends \
        curl \
        unzip \
        make
RUN curl -SLO http://dl.google.com/android/repository/android-ndk-$NDK_VERSION-linux.zip
RUN unzip android-ndk-$NDK_VERSION-linux.zip
RUN mv ./android-ndk-$NDK_VERSION /opt/ndk
RUN rm android-ndk-$NDK_VERSION-linux.zip
ENV ANDROID_NDK_ROOT /opt/ndk
